"""Domain models, split by bounded context.

Historically a single ``models.py`` module. Kept importable exactly as before
(``from models import X``) via this package's re-exports, so no call site had to
change when the file was split.
"""

from .annexe import DEFAULT_ANNEXE_RUBRIQUES, AnnexeRubrique, AnnexeRubriqueRead
from .apikey import ApiKey, ApiKeyCreated, ApiKeyRead
from .association import (
    Association,
    AuditLog,
    AuditLogRead,
    LogEntry,
    LogEntryRead,
    RefreshSession,
)
from .banque import (
    ImportReleve,
    ImportReleveRead,
    LigneBancaire,
    LigneBancaireRead,
    LigneBancaireStatut,
    RapprochementCompteRead,
    RapprochementSuggestion,
)
from .budget import (
    Budget,
    BudgetRead,
    BudgetUpsert,
    LigneBudget,
    LigneBudgetInput,
    LigneBudgetRead,
)
from .categorie import CategorieSaisie, CategorieSaisieRead, SensCategorie
from .common import utcnow
from .ecriture import (
    BalanceCompteRead,
    Ecriture,
    EcritureDetailRead,
    EcritureListItem,
    EcritureOrigine,
    EcritureRead,
    EcritureStatut,
    GrandLivreLigneRead,
    LigneEcriture,
    LigneEcritureRead,
    LigneJournalRead,
    ModeReglement,
)
from .evenement import Evenement, EvenementRead, EvenementStatut
from .identity import (
    Invitation,
    Membership,
    MembershipRead,
    MembershipStatus,
    PermissionPreset,
    Role,
    User,
)
from .justificatif import Justificatif, JustificatifRead
from .recu import (
    DonRead,
    FormeDon,
    RecuFiscal,
    RecuFiscalLigne,
    RecuFiscalRead,
)
from .recurrence import (
    GenerationResult,
    Periodicite,
    Recurrence,
    RecurrenceMode,
    RecurrenceRead,
)
from .referentiel import (
    AffectationResultat,
    ClotureResult,
    Compte,
    CompteRead,
    CompteTresorerieRead,
    CompteType,
    Exercice,
    ExerciceCreate,
    ExerciceRead,
    ExerciceStatut,
    Journal,
    JournalRead,
    TypeTresorerie,
)
from .synthese import (
    AlerteBudget,
    AlerteEvenement,
    AlerteExercice,
    BudgetSynthese,
    CourbePoint,
    RepartitionCategorieItem,
    RepartitionEvenementItem,
    RepartitionTresorerieItem,
    SyntheseAlertes,
    SyntheseRead,
    SyntheseResultat,
)
from .tiers import Tiers, TiersRead, TypeTiers

__all__ = [
    "AffectationResultat",
    "AlerteBudget",
    "AlerteEvenement",
    "AlerteExercice",
    "AnnexeRubrique",
    "AnnexeRubriqueRead",
    "ApiKey",
    "ApiKeyCreated",
    "ApiKeyRead",
    "Association",
    "AuditLog",
    "AuditLogRead",
    "BalanceCompteRead",
    "Budget",
    "BudgetRead",
    "BudgetSynthese",
    "BudgetUpsert",
    "CategorieSaisie",
    "CategorieSaisieRead",
    "ClotureResult",
    "Compte",
    "CompteRead",
    "CompteTresorerieRead",
    "CompteType",
    "CourbePoint",
    "DEFAULT_ANNEXE_RUBRIQUES",
    "Ecriture",
    "EcritureDetailRead",
    "EcritureListItem",
    "EcritureOrigine",
    "EcritureRead",
    "EcritureStatut",
    "Evenement",
    "EvenementRead",
    "EvenementStatut",
    "Exercice",
    "ExerciceCreate",
    "ExerciceRead",
    "ExerciceStatut",
    "GenerationResult",
    "GrandLivreLigneRead",
    "ImportReleve",
    "ImportReleveRead",
    "Invitation",
    "Journal",
    "JournalRead",
    "Justificatif",
    "JustificatifRead",
    "LigneBancaire",
    "LigneBancaireRead",
    "LigneBancaireStatut",
    "LigneBudget",
    "LigneBudgetInput",
    "LigneBudgetRead",
    "LigneEcriture",
    "LigneEcritureRead",
    "LigneJournalRead",
    "LogEntry",
    "LogEntryRead",
    "Membership",
    "MembershipRead",
    "MembershipStatus",
    "ModeReglement",
    "DonRead",
    "FormeDon",
    "RecuFiscal",
    "RecuFiscalLigne",
    "RecuFiscalRead",
    "PermissionPreset",
    "Periodicite",
    "RapprochementCompteRead",
    "RapprochementSuggestion",
    "Recurrence",
    "RecurrenceMode",
    "RecurrenceRead",
    "RefreshSession",
    "RepartitionCategorieItem",
    "RepartitionEvenementItem",
    "RepartitionTresorerieItem",
    "Role",
    "SensCategorie",
    "SyntheseAlertes",
    "SyntheseRead",
    "SyntheseResultat",
    "Tiers",
    "TiersRead",
    "TypeTiers",
    "TypeTresorerie",
    "User",
    "utcnow",
]
